project_id = "nlrdiznleytpuwvugloi"

[functions.recommend-threshold]
verify_jwt = false

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.send-verification]
verify_jwt = false

[functions.send-welcome]
verify_jwt = false

[functions.send-deal]
verify_jwt = false

[functions.track-email-open]
verify_jwt = false

[functions.track-email-click]
verify_jwt = false

[functions.check-flight-prices]
verify_jwt = false
